<?php

/**
 * @file
 * Contains happy_block.module
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */

function happy_block_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    // Main module help for the happy_block module.
    case 'help.page.happy_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Implements a block') . '</p>';
      return $output;
    break;
  }
}

/**
 * Implements hook_theme().
 */

function happy_block_theme()
{
  $theme = [];

  return $theme;
}
