<?php

/**
 * @file
 * Contains happy_book.module
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */

function happy_book_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    // Main module help for the happy_book module.
    case 'help.page.happy_book':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module that implements a new book entity type.') . '</p>';
      return $output;
    break;
  }
}

/**
 * Implements hook_theme().
 */

function happy_book_theme()
{
  $theme = [];

  $theme['author_entity'] = array(
    'render element' => 'elements',
    'file' => 'author_entity.page.inc',
    'template' => 'author_entity',
  );

  return $theme;
}
