<?php

/**
 * @file
 * Contains happy_alexandrie.module
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */

function happy_alexandrie_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the happy_alexandrie module.
    case 'help.page.happy_alexandrie':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module that implements a new book entity type.') . '</p>';
      return $output;
      break;
  }
}

/**
 * Implements hook_theme().
 */

function happy_alexandrie_theme() {
  $theme = [];

  $theme['author_entity'] = array(
    'render element' => 'elements',
    'file' => 'author_entity.page.inc',
    'template' => 'author_entity',
  );

  $theme['happy_cover'] = array(
    'variables' => array('cover_url' => '', 'cover_title' => ''),
    'template' => 'happy-cover',
  );

  return $theme;
}

/**
 * Implements hook_entity_view_alter().
 */
function happy_alexandrie_entity_view_alter(&$build, $type) {
  if (isset($build['#theme']) && $build['#theme'] == 'node') {
    $build['#attached']['library'][] = 'happy_alexandrie/local-favorite';
  }
}